import type { PortfolioContent } from "@/lib/cms-types";

export const defaultPortfolioContent: PortfolioContent = {
  hero: {
    title: "Portfolio",
    sub: "Brands, events, spaces, and commercial visual stories",
    image: "/uploads/site-images/conference-panel.jpg",
  },
  tabs: ["All", "Events", "Hospitality", "Property", "Editorial"],
  projects: [
    {
      title: "Conferences & Exhibitions",
      category: "Events",
      filter: "Events",
      href: "/portfolio",
      imageAlt: "Conference photography portfolio project",
      image: "/uploads/site-images/event-lobby.jpg",
    },
    {
      title: "Corporate Events",
      category: "Events",
      filter: "Events",
      href: "/portfolio",
      imageAlt: "Corporate event photography portfolio project",
      image: "/uploads/site-images/conference-panel.jpg",
    },
    {
      title: "Commercial & Studio Photography",
      category: "Commercial",
      filter: "All",
      href: "/portfolio",
      imageAlt: "Commercial studio photography portfolio project",
      image: "/uploads/site-images/team-portrait.jpg",
    },
    {
      title: "Food & Hospitality Visuals",
      category: "Hospitality",
      filter: "Hospitality",
      href: "/portfolio",
      imageAlt: "Food and hospitality visuals portfolio project",
      image: "/uploads/site-images/food-detail.jpg",
    },
    {
      title: "Real Estate & Property Marketing",
      category: "Property",
      filter: "Property",
      href: "/portfolio",
      imageAlt: "Real estate photography portfolio project",
      image: "/uploads/site-images/property-aerial.jpg",
    },
    {
      title: "Architecture & Interior Photography",
      category: "Property",
      filter: "Property",
      href: "/portfolio",
      imageAlt: "Architecture and interior photography portfolio project",
      image: "/uploads/site-images/conference-room.jpg",
    },
    {
      title: "Fashion & Editorial Production",
      category: "Editorial",
      filter: "Editorial",
      href: "/portfolio",
      imageAlt: "Fashion editorial production portfolio project",
      image: "/uploads/site-images/team-portrait.jpg",
    },
    {
      title: "Video Production",
      category: "Commercial",
      filter: "All",
      href: "/portfolio",
      imageAlt: "Video production portfolio project",
      image: "/uploads/site-images/conference-panel.jpg",
    },
    {
      title: "360-degree Photography & Virtual Tours",
      category: "Property",
      filter: "Property",
      href: "/portfolio",
      imageAlt: "Virtual tour portfolio project",
      image: "/uploads/site-images/property-aerial.jpg",
    },
  ],
};
